# 적용하는 테마
remote_theme: thelehhman/texture
theme: texture

title: Luce in altis
author: KIM KI HWAN
email: luceinaltis2020@naver.com
description: 컴퓨터 배우기

show_excerpts: true # set to true to show excerpts on the homepage
baseurl:
url: luceinaltis.github.io


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Luce in altis
  tagline: 모든 일에 최선을 다하자
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: 
    github:  luceinaltis
    linkedIn: 
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed