name: CI

on:
  push:
    branches: [ master ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
      - run: npm install
      - run: npm run build
      - run:  git add -f out/ 
      - run:  git commit -m "deploy Next.js to gh-pages"
      - run:  git subtree push --prefix out origin gh-pages
      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}
