name: BUILD_DEPLOY

on:
  push:
    branches: [ master ]

jobs:
  BUILD_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run:  |          
          git config user.name luceinaltis
          git config user.email luceinaltis2020@naver.com

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm run build
      - run: touch out/CNAME && echo "www.luce.today" > out/CNAME
      - name: 사이트맵 생성
        run: node scripts/sitemap.js
      - run: git add -f out/
      - run: git commit -m "Deploy Next.js to gh-pages"
      - run: git push origin `git subtree split --prefix out master`:gh-pages --force