name: BUILD_DEPLOY

on:
  push:
    branches: [ master ]

jobs:
  BUILD_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run:  |          
          git config user.name luceinaltis
          git config user.email luceinaltis2020@naver.com
      - uses: actions/cache@v2
        id: cache-build
        with:
          path: node_modules
          key: ${{ runner.os }}-modules
      - run: npm install
      - run: npm run build
      - run: touch out/CNAME && echo "www.luce.today" > out/CNAME
      - run: git reset --hard "origin/gh-pages"
      - run: git add -f out/
      - run: git commit -m "Deploy Next.js to gh-pages"
      - run: git subtree push --prefix out origin gh-pages
