name: BUILD_DEPLOY

on:
  push:
    branches: [ master ]

jobs:
  BUILD_DEPLOY:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{secrets.PAT}}
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}

      - run:  |          
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm install
      - run: npm run build
      - run:  git add -f out/ 
      - run:  git commit -m "deploy Next.js to gh-pages"
      - run:  git subtree push --prefix out origin gh-pages
      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}
